projectcamp/src/main/java/vn/viettel/campaign/entities/Rule.java
/*
 * Copyright 2009-2014 PrimeTek.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package vn.viettel.campaign.entities;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.io.Serializable;

/**
 * @author truongbx
 */
@Entity
@Table(name = "RULE")
@Getter
@Setter
public class Rule extends BaseCategory implements Serializable {

    @Id
    @Column(name = "RULE_ID")
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long ruleId;
    @Column(name = "DESCRIPTION")
    public String description;
    @Column(name = "RULE_NAME")
    public String ruleName;
    @Column(name = "CATEGORY_ID")
    private long categoryId;
    //HaBM2: Update change structure
    @Column(name = "CDR_SERVICE_IDS")
    private String cdrServiceId;
    
    @Transient
    public String segmentName;
    @Transient
    public long segmentId;
    @Transient
    public Integer priority;
    @Transient
    public Segment segment;
    @Transient
    private String name;
    
    public Rule() {
    }

    public Segment getSegment() {
        return segment;
    }

    public void setSegment(Segment segment) {
        if (segment!= null){
            this.segmentName = segment.getSegmentName();
            this.segmentId = segment.getSegmentId();
        }
        this.segment = segment;
    }


    public void setName(String name) {
        this.name = name;
    }
    @Override
    public long getParentId() {
        return getCategoryId();
    }

    @Override
    public String getTreeType() {
        return "rule_online";
    }

    @Override
    public void setParentId(Long id) {
        setCategoryId(id);
    }

    @Override
    public String getName() {
        return this.ruleName;
    }

    @Override
    public Class getParentType() {
        return Category.class;
    }
    public void asMap(Rule rule){
        this.ruleId = rule.getRuleId();
        this.ruleName = rule.getRuleName();
        this.description = rule.getDescription();
        this.categoryId = rule.getCategoryId();
        this.cdrServiceId = rule.getCdrServiceId();
    }
}

projectcamp/src/main/java/vn/viettel/campaign/entities/Zone.java
package vn.viettel.campaign.entities;
import java.io.Serializable;
import javax.persistence.*;
import java.util.Date;

/**
*
* @author truongbx
*/
@Entity
@Table(name = "zone")
public class Zone extends BaseCategory implements Serializable, TreeItemBase{
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "ZONE_ID")
  private long zoneId;
  @Column(name = "ZONE_MAP_ID")
  private Long zoneMapId;
  @Column(name = "ZONE_NAME")
  private String zoneName;
  @Column(name = "ZONE_CODE")
  private String zoneCode;
  @Column(name = "DESCRIPTION")
  private String description;
  @Column(name = "CATEGORY_ID")
  private Long categoryId;
  @Column(name = "IS_MATCHING")
  private Long isMatching;
  @Transient
  private String name;

  public String getName() {
    return zoneName;
  }

  public void setName(String name) {
    this.name = name;
  }

  public long getZoneId() {
    return zoneId;
  }

  public void setZoneId(long zoneId) {
    this.zoneId = zoneId;
  }


  public Long getZoneMapId() {
    return zoneMapId;
  }

  public void setZoneMapId(Long zoneMapId) {
    this.zoneMapId = zoneMapId;
  }


  public String getZoneName() {
    return zoneName;
  }

  public void setZoneName(String zoneName) {
    this.zoneName = zoneName;
  }


  public String getZoneCode() {
    return zoneCode;
  }

  public void setZoneCode(String zoneCode) {
    this.zoneCode = zoneCode;
  }


  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public Long getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(Long categoryId) {
    this.categoryId = categoryId;
  }


  public Long getIsMatching() {
    return isMatching;
  }

  public void setIsMatching(Long isMatching) {
    this.isMatching = isMatching;
  }
  public String getFilter() {
    return getName();
  }

   @Override
    public long getParentId() {
        return this.getCategoryId();
    }

    @Override
    public void setParentId(Long id) {
        setCategoryId(id);
    }

    @Override
    public String getTreeType() {
       return "object";
    }

    @Override
    public Class getParentType() {
        return Zone.class;
    }
}

projectcamp/src/main/java/vn/viettel/campaign/controller/RuleOfflineController.java
package vn.viettel.campaign.controller;

import lombok.Getter;
import lombok.Setter;
import org.primefaces.PrimeFaces;
import org.primefaces.model.DualListModel;
import org.primefaces.model.TreeNode;
import org.springframework.beans.factory.annotation.Autowired;
import vn.viettel.campaign.common.DataUtil;
import vn.viettel.campaign.constants.Constants;
import vn.viettel.campaign.entities.*;
import vn.viettel.campaign.service.CampaignOnlineService;
import vn.viettel.campaign.service.RuleServiceInterface;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.*;
import javax.faces.bean.ManagedProperty;
import org.primefaces.model.DefaultTreeNode;
import vn.viettel.campaign.validate.CheckOnEdit;

/**
 * @author truongbx
 * @date 9/15/2019
 */
@ManagedBean(name = "ruleOfflineController")
@ViewScoped
@Getter
@Setter
public class RuleOfflineController extends BaseCategoryController<Rule> implements Serializable {

    TreeNode parentNode;
    
    @Autowired
    private CampaignOnlineService campaignOnlineService;
    @Autowired
    private RuleServiceInterface ruleServiceImpl;
    private DualListModel<ResultTable> resultTablePickingList = new DualListModel<>();
    private List<ResultTable> resultTable = new ArrayList<>();
    private List<BaseCategory> resultTableAllData = new ArrayList<>();
    public TreeNode rootResultTable;
    private TreeNode[] selectedResultTable;
    private Map<Long, TreeNode> mapResultTableNode = new HashMap<>();

    private String editObject;
    @ManagedProperty(value = "#{resultTableController}")
    ResultTableController resultTableController;

    @ManagedProperty(value = "#{conditionTableController}")
    ConditionTableController conditionTableController;

    @ManagedProperty(value = "#{preProcessController}")
    PreProcessController preProcessController;

    @ManagedProperty(value = "#{preProcessNumberController}")
    PreProcessNumberController preProcessNumberController;

    @ManagedProperty(value = "#{preProcessExistElementController}")
    PreProcessExistElementController preProcessExistElementController;

    @ManagedProperty(value = "#{preProcessTimeController}")
    PreProcessTimeController preProcessTimeController;

    @ManagedProperty(value = "#{preProcessDateController}")
    PreProcessDateController preProcessDateController;

    @ManagedProperty(value = "#{preProcessNumberRangeController}")
    PreProcessNumberRangeController preProcessNumberRangeController;

    @ManagedProperty(value = "#{preProcessCompareNumberController}")
    PreProcessCompareNumberController preProcessCompareNumberController;

    @ManagedProperty(value = "#{preProcessZoneController}")
    PreProcessZoneController preProcessZoneController;

    @ManagedProperty(value = "#{preProcessSameElementController}")
    PreProcessSameElementController preProcessSameElementController;

    @Override
    public void init() {
        this.categoryType = Constants.CatagoryType.CATEGORY_RULE_OFFLINE_TYPE;
        this.currentClass = Rule.class;
        resultTable = new ArrayList<>();
    }

    @Override
    public void initCurrentValue() {
        currentValue = ruleServiceImpl.getNextSequense();
    }

    @Override
    public boolean onValidateObject() {
        if (!validInputField(this.currentValue.getRuleName(), "Rule name", true, true, true)) {
            return false;
        }
        if (!validInputField(this.currentValue.getDescription(), "Description", false, true, true)) {
            return false;
        }
        if (campaignOnlineService.checExisRuleName(this.currentValue.getRuleName(), this.currentValue.getRuleId())) {
            errorMsgParams(Constants.REMOTE_GROWL, utilsService.getTex("check.duplicate"), "Rule name");
            return false;
        }

        if (this.currentValue.getCategoryId() == 0) {
            errorMsg(Constants.REMOTE_GROWL, utilsService.getTex("check.rule.category"));
            return false;
        }
        if (resultTable.size() == 0) {
            errorMsgParams(Constants.REMOTE_GROWL, utilsService.getTex("check.empty"), "Result table");
            return false;
        }
        List<CdrService> cdrServices = new ArrayList<>();
        String ids = "";
        for (CdrService cdrService : cdrServices) {
            ids += "," + cdrService.getCdrServiceId();
        }
        this.currentValue.setCdrServiceId(ids.replaceFirst(",", ""));
        return true;
    }

    @Override
    public boolean doDelete() {
        return ruleServiceImpl.onDeleteRule(this.currentValue.getRuleId());
    }

    @Override
    public boolean onSaveObject() {
        DataUtil.trimObject(this.currentValue);
        this.currentValue.setCdrServiceId("-1");
        return ruleServiceImpl.onSaveRule(this.currentValue, resultTable);
    }

    @Override
    public void doEdit() {
        resultTable = campaignOnlineService.getListResultByRuleId(this.currentValue.getRuleId());
        initResultTableTree();
    }

    @Override
    public boolean onUpdateObject() {
        DataUtil.trimObject(this.currentValue);
		this.currentValue.setCdrServiceId("-1");
        return ruleServiceImpl.onUpdateRule(this.currentValue, resultTable);
    }

    @Override
    public void rollbackData() {
        Rule data = ruleServiceImpl.findById(this.currentValue.getRuleId());
        this.currentValue.asMap(data);
    }

    @Override
    public void doAdd() {
        resultTable = new ArrayList<>();
        initResultTableTree();
    }

    public void prepareDataToShowResultTablePopup() {
        initResultTableTree();
        createSelectedTreeNode();
    }

    public void removeResultTable(ResultTable o) {
        resultTable.remove(o);
        resultTableAllData.add(o);
    }

    public void moveResulTableUp(ResultTable o) {
        int i = resultTable.indexOf(o);
        if (i > 0) {
            resultTable.remove(o);
            resultTable.add(i - 1, o);
        }
    }

    public void moveResulTableDown(ResultTable o) {
        int i = resultTable.indexOf(o);
        if (i < resultTable.size() - 1) {
            resultTable.remove(o);
            resultTable.add(i + 1, o);
        }
    }

    public boolean onSaveResultTable() {
        if (selectedResultTable.length == 0) {
            errorMsgParams(Constants.REMOTE_GROWL, utilsService.getTex("check.empty"), "Result table");
            return false;
        }
        List<ResultTable> tempResultTable = new ArrayList<>();
        for (TreeNode treeNode : selectedResultTable) {
            Object data = treeNode.getData();
            if (data instanceof Category && treeNode.getChildren().isEmpty()) {
                errorMsgParams(Constants.REMOTE_GROWL, utilsService.getTex("check.resultable.category"));
                return false;
            } else if (data instanceof ResultTable) {
                ResultTable resultTable = (ResultTable) data;
                tempResultTable.add(resultTable);
            }
        }
        resultTable.clear();
        resultTable.addAll(tempResultTable);
        return true;
    }

    public void createMapResulTableTreeNode(TreeNode node, Map<Long, TreeNode> mapResultTableNode) {
        if (node == null) {
            return;
        }
        Object data = node.getData();
        if (data instanceof ResultTable) {
            ResultTable resultTable = (ResultTable) data;
            mapResultTableNode.put(resultTable.getResultTableId(), node);
            return;
        }
        for (TreeNode treeNode : node.getChildren()) {
            createMapResulTableTreeNode(treeNode, mapResultTableNode);

        }
    }

    public void createSelectedTreeNode() {
        selectedResultTable = new TreeNode[resultTable.size()];
        for (int i = 0; i < resultTable.size(); i++) {
            TreeNode treeNode = mapResultTableNode.get(resultTable.get(i).getResultTableId());
            if (treeNode != null){
            treeNode.setSelected(true);
            expandCurrentNode(treeNode);
            selectedResultTable[i] = treeNode;
            }
        }
    }

    public TreeNode[] getSelectedResultTable() {
        return selectedResultTable;
    }

    public void setSelectedResultTable(TreeNode[] selectedResultTable) {
        this.selectedResultTable = selectedResultTable;
    }

    public void initResultTableTree() {
        List<Category> categories = categoryService.getCategoryByType(Constants.CatagoryType.CATEGORY_RESULT_TABLE_TYPE);
        List<Long> longs = new ArrayList<>();
        if (!categories.isEmpty()) {
            categories.forEach(item -> longs.add(item.getCategoryId()));
        }
        this.resultTableAllData = categoryService.getDataFromCatagoryId(longs, ResultTable.class.getSimpleName());
        rootResultTable = treeService.createTreeCategoryAndChild(categories, resultTableAllData);
        rootResultTable.setExpanded(true);
        mapResultTableNode = new HashMap<>();
        createMapResulTableTreeNode(rootResultTable, mapResultTableNode);
    }
    
    public void prepareEditWhenClick() {
        CheckOnEdit.onEdit = "rule_offline";
        prepareEdit();
        this.action = false;
    }

    public void prepareEditFromContextMenu() {
        CheckOnEdit.onEdit = "rule_offline";
        prepareEdit();
        this.action = true;

    }

    public void prepareEdit() {
        
        this.parentNode = selectedNode.getParent();
        if ("category".equals(this.selectedNode.getType())) {
            prepareEditCategory();
            PrimeFaces.current().executeScript("PF('carDialog').show();");
        }
        if ("rule_online".equals(selectedNode.getType())) {
            this.editObject = "rule_online";
            selectedNode.getChildren().clear();
            doAddResultTableToRule(selectedNode);
            selectedNode.setExpanded(true);
            onEditObject();
        }

        if ("result".equals(selectedNode.getType())) {
            this.editObject = "result";

projectcamp/src/main/webapp/ruleOffline/AddResultTablePopup.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <p:dialog header="Add Result table" onShow="onShownResultTable()" widgetVar="resultTablePopup" id="resultTablePopup" responsive="true" style="width: 1000px;overflow-y: hidden" modal="true" dynamic="true"  >
        <f:facet name="header">
            <i class="fa fa-list" style="font-size: 14px;"></i>
            <h:outputText value="Add Result table" style="margin-left:10px;"/>
        </f:facet>
        <h:form id="resultTabletForm">
            <p:tree filterMatchMode="contains" id="resultTableTree" var="node"
                    value="#{ruleOfflineController.rootResultTable}"
                    filterBy="#{node.filter}"
                    selectionMode="checkbox"
                    selection="#{ruleOfflineController.selectedResultTable}"
                    style=" border: 0px solid; padding: 0px;width: 500px;height:550px ;overflow-y: auto;">

                <p:treeNode type="category" expandedIcon="ui-icon-folder-open"
                            collapsedIcon="ui-icon-folder-collapsed">
                    <h:outputText value="#{node.name}"/>
                </p:treeNode>

                <p:treeNode type="resultTable" icon="ui-icon-document">
                    <h:outputText value="#{node.name}"/>
                </p:treeNode>
            </p:tree>
            <div class="card card-w-title">
                <p:outputPanel class="ui-g-12 ui-lg-12">
                    <p:commandButton value="Apply"
                                     icon="fa fa-floppy-o"
                                     action="#{ruleOfflineController.onSaveResultTable()}"
                                     style="width:auto;float: right;"
                                     update="@([id$=resultTable]),@([id$=remoteGrowl])"
                                     oncomplete="if (!args.validationFailed) PF('resultTablePopup').hide()"/>
                </p:outputPanel>
            </div>
        </h:form>
    </p:dialog>
</html>

projectcamp/src/main/webapp/ruleOffline/RuleAndCategoryTree.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <h:form id="fromTree">

<!--        <p:toolbar styleClass="toolbar">
            <f:facet name="left">
                <p:outputLabel value="List ocs behaviour" 
                               style="float: left; font-weight: bold; font-size: 14px"/>
            </f:facet>
        </p:toolbar>-->

        <!--habm2-start-->
        <div class="title-wrap">
            <div class="title-name">Rule offline</div>
        </div>
        <!--habm2-end-->
        
        <p:tree filterMatchMode="contains" id="treeCategory" var="node"
                value="#{ruleOfflineController.rootNode}"
                filterBy="#{node.filter}"
                selectionMode="single"
                selection="#{ruleOfflineController.selectedNode}"
                style="height: calc(100vh - 101px) !important; overflow: auto;">
            <p:ajax event="select" 
                    listener="#{ruleOfflineController.prepareEditWhenClick()}"
                    update="@([id$=content]), @([id$=carDialog])"/>

            <p:treeNode type="category" expandedIcon="ui-icon-folder-open"
                        collapsedIcon="ui-icon-folder-collapsed">
                <h:outputText value="#{node.name}"/>
            </p:treeNode>

            <p:treeNode type="rule_online" icon="ui-icon-document">
                <h:outputText value="#{node.name}" />
            </p:treeNode>
            
            <p:treeNode type="result" icon="ui-icon-document">
                <h:outputText value="#{node.name}" />
            </p:treeNode>
            
            <p:treeNode type="condition" >
                <h:outputText value="#{node.name}" />
            </p:treeNode>
            
            <p:treeNode type="ppu" icon="ui-icon-document">
                <h:outputText value="#{node.name}" />
            </p:treeNode>
            <p:ajax event="expand" listener="#{ruleOfflineController.onNodeExpand}"></p:ajax>
            <p:ajax event="collapse" listener="#{ruleOfflineController.onNodeCollapse}"></p:ajax>
        </p:tree>

        <p:contextMenu for="treeCategory" nodeType="category" style="width: auto;">
            <p:menuitem icon="fa fa-floppy-o"
                        value="Create category"
                        action="#{ruleOfflineController.prepareCreateCategory()}"
                        update="@([id$=carDialog]),@([id$=categoryConfirm])"
                        oncomplete="PF('carDialog').show();"/>
            <p:menuitem icon="fa fa-refresh"
                        value="Edit category"
                        action="#{ruleOfflineController.prepareEditCategory()}"
                        update="@([id$=carDialog]),@([id$=categoryConfirm])"
                        oncomplete="PF('carDialog').show();"/>
            <p:menuitem icon="fa fa-trash"
                        value="Delete category"
                        action="#{ruleOfflineController.doDeleteCategory()}"
                        update="@([id$=fromTree]),@([id$=remoteGrowl])">
                <p:confirm header="Confirmation" message="You definitely want to delete ?" icon="ui-icon-alert"/>
            </p:menuitem>
            <p:menuitem icon="fa fa-plus" value="Create rule offline" action="#{ruleOfflineController.prepareAddObject()}"
                        update="@([id$=mainContent])"/>
        </p:contextMenu>

        <p:contextMenu for="treeCategory" nodeType="rule_online" style="width: auto">
            <p:menuitem icon="fa fa-refresh"
                        value="Edit rule"
                        action="#{ruleOfflineController.prepareEditFromContextMenu()}"
                        update="@([id$=content])"/>
            <p:menuitem icon="fa fa-trash"
                        value="Delete rule"
                        action="#{ruleOfflineController.onDeleteObject()}"
                        update="@([id$=treeCategory]),@([id$=remoteGrowl]),@([id$=mainContent])">
                <p:confirm header="Confirmation" message="Do you want to delete this rule offline?" icon="ui-icon-alert"/>
            </p:menuitem>
        </p:contextMenu>

    </h:form>

    <ui:include src="categoryCreateOrEditPopup.xhtml"/>
    
</html>

projectcamp/src/main/webapp/ruleOffline/RuleOffline.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                template="/WEB-INF/template_object.xhtml">

    <ui:define name="title">Rule offline</ui:define>

    <ui:define name="viewname">Rule offline</ui:define>
 
    <ui:define name="head">
        <style>
            body .ui-outputlabel {
                padding-bottom: 5px;
            }

            #basic1 .ui-panel-titlebar {
                padding: 0px;
                /*border-bottom: 0px solid;*/
            }

            body .ui-panel .ui-panel-content {
                padding: 0px;
            }
            .ocsTabview ul{
                width: fit-content;
            }
        </style>
        <script type="text/javascript">
            function onShownResultTable() {
                console.log("messsage");
                $('#resultTablePopup .ui-icon-folder-collapsed').siblings().each(function( index ) {
                    if($( this ).hasClass( "ui-chkbox" )){
                        $( this ).css("display", "none");
                    }
                });

                $('#resultTablePopup .ui-icon-folder-open').siblings().each(function( index ) {
                    if($( this ).hasClass( "ui-chkbox" )){
                        $( this ).css("display", "none");
                    }
                });
            }
        </script>
    </ui:define>

    <ui:define name="content" >      
        <p:outputPanel class="ui-g ui-fluid" id="content">
            <p:outputPanel class="ui-g-12 ui-lg-3 panel_content" style=" margin-top: -20px">
                <ui:include src="RuleAndCategoryTree.xhtml"/>
            </p:outputPanel>
            <p:outputPanel class="ui-g-12 ui-lg-9 panel_content" id="mainContent">
                <ui:include src="RuleContent.xhtml"/>
            </p:outputPanel>
        </p:outputPanel> 
    </ui:define>
</ui:composition>

projectcamp/src/main/webapp/ruleOffline/categoryCreateOrEditPopup.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <p:dialog header="#{ruleOfflineController.updateCategory eq false ? 'Create category' :'Update category'}"
              widgetVar="carDialog" id="carDialog" responsive="true" modal="true">
        <f:facet name="header">
            <i class="fa fa-list" style="font-size: 14px;"></i>
            <h:outputText value="#{ruleOfflineController.updateCategory eq false ? 'Create category' :'Update category'}" style="margin-left:10px;"/>
        </f:facet>
        <h:form id="catagoryfrm" style="width: 635px !important">
            <p:outputPanel class="ui-g ui-fluid">
                <p:outputPanel class="ui-g-12 ui-lg-6">
                    <p:outputLabel value="Category id"/><span style="color: red">*</span>
                    <div class="spacerHeight"/>
                    <p:inputText onchange="this.value = this.value.trim()" placeholder="Category id"
                                 id="categoryId"
                                 readonly="true"
                                 value="#{ruleOfflineController.category.categoryId}"
                                 requiredMessage="Category id is required"
                                 validatorMessage="Category id not contains '%' character">
                        <f:validateRegex pattern="^[^%]*$"/>
                    </p:inputText>
                </p:outputPanel>
                <p:outputPanel class="ui-g-12 ui-lg-6">
                    <p:outputLabel value="Category name"/><span style="color: red">*</span>
                    <div class="spacerHeight"/>
                    <p:inputText onchange="this.value = this.value.trim()" placeholder="Category name"
                                 id="categoryName"
                                 value="#{ruleOfflineController.category.name}"
                                 title="#{ruleOfflineController.category.name}"
                                 requiredMessage="Category name is required"  autocomplete="off">
                        <p:ajax update="@this" process="@this" global="false"/>
                    </p:inputText>
                </p:outputPanel>
                <p:outputPanel class="ui-g-12 ui-lg-6">
                    <p:outputLabel value="Category type"/><span style="color: red">*</span>
                    <div class="spacerHeight"/>
                    <p:inputText onchange="this.value = this.value.trim()" placeholder="Category type"
                                 readonly="true"
                                 id="categoryType"
                                 required="true"
                                 value="Rule Offline"
                                 requiredMessage="Category type is require"/>
                </p:outputPanel>

                <p:outputPanel class="ui-g-12 ui-lg-6" rendered="#{ruleOfflineController.category.parentId != null}">
                    <p:outputLabel value="Parent category"/>
                    <div class="spacerHeight"/>
                    <p:selectOneMenu  syncTooltip="true"  filterMatchMode="contains"  filter="true" style="margin-bottom:10px;"
                                     value="#{ruleOfflineController.category.parentId}"
                                     id="parentCategory"
                                     rendered="#{ruleOfflineController.updateCategory eq false}">
                        <f:selectItems value="#{ruleOfflineController.categories}"
                                       var="item"
                                       itemLabel="#{item.name}" itemDescription="#{item.name}" 
                                       itemValue="#{item.categoryId}"/>
                    </p:selectOneMenu>
                    <p:selectOneMenu  syncTooltip="true"  filterMatchMode="contains"  filter="true" style="margin-bottom:10px;"
                                     value="#{ruleOfflineController.category.parentId}"
                                     id="parentCategoryEdit"
                                     rendered="#{ruleOfflineController.updateCategory eq true}">

                        <f:selectItems value="#{ruleOfflineController.categories}"
                                       var="item"
                                       itemLabel="#{item.name}" itemDescription="#{item.name}" 
                                       itemValue="#{item.categoryId}"/>
                    </p:selectOneMenu>
                </p:outputPanel>
                <p:outputPanel class="ui-g-12 ui-lg-6"></p:outputPanel>
            </p:outputPanel>

            <div class="card card-w-title">
                <p:outputPanel class="ui-g-12 ui-lg-12">
                    <p:commandButton icon="fa fa-remove" value="Cancel"
                                     style="width:auto;float: right;"
                                     process="@this"
                                     oncomplete="PF('carDialog').hide();"/>
                    <p:commandButton action="#{ruleOfflineController.validateCategory()}"
                                     style="width:auto;float: right;" 
                                     icon="fa fa-floppy-o" value="Save"
                                     process="@([id$=catagoryfrm])"
                                     update="@([id$=remoteGrowl])"
                                     oncomplete="if (!args.validationFailed) PF('dlgConfirm').show();">
                    </p:commandButton>
                </p:outputPanel>
            </div>
        </h:form>
    </p:dialog>

    <p:dialog header="Confirmation" widgetVar="dlgConfirm" modal="true" height="100" id="categoryConfirm">
        <h:outputText value="#{ruleOfflineController.updateCategory eq false ? 'Are you sure to create this Category?' : 'Are you sure to edit this Category?'}" />

        <div class="card card-w-title">
            <p:outputPanel class="ui-g-12 ui-lg-12">
                <p:commandButton value="No"
                                 style="width:auto;float: right;"
                                 process="@this"
                                 oncomplete="PF('dlgConfirm').hide();"/>

                <p:commandButton action="#{ruleOfflineController.doSaveOrUpdateCategory()}"
                                 style="width:auto;float: right;"
                                 value="Yes"
                                 process="@([id$=catagoryfrm]),@this"
                                 update="@([id$=fromTree]),@([id$=remoteGrowl])"
                                 oncomplete="PF('dlgConfirm').hide();PF('carDialog').hide();">
                </p:commandButton>
            </p:outputPanel>
        </div>
    </p:dialog>
</html>