projectcamp/src/main/java/vn/viettel/campaign/dto/Path.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.viettel.campaign.dto;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import vn.viettel.campaign.common.DataUtil;
import vn.viettel.campaign.entities.EvaluationInputObject;

/**
 *
 * @author SON
 */
public class Path {

    private int id;
    private String ObjectName;
    private List<EvaluationInputObject> lstEvaluationInputObject = new ArrayList<>();
    private String filter;
    private EvaluationInputObject inputObject = new EvaluationInputObject();

    private String dataCondition;
    private String dataFunction;

    public static boolean isStringNullOrEmpty1(String input) {
        if (input == null || input.trim().equalsIgnoreCase("") || input.trim().equalsIgnoreCase(" ")) {
            return true;
        }
        return false;
    }

    public String getDataCondition() {
        if (isStringNullOrEmpty1(this.dataCondition)) {
            this.dataCondition = "";
            if (getFilter() != null) {
                String[] result = getFilter().split(";");
                if (result.length == 2 || result.length == 1) {
                    dataCondition = result[0];
                }
            }
        }
        return dataCondition;
    }

    public void setDataCondition(String dataCondition) {
        this.dataCondition = dataCondition;
    }

    public String getDataFunction() {
        if (DataUtil.isStringNullOrEmpty(this.dataFunction)) {
            this.dataFunction = "";
            if (getFilter() != null) {
                String[] result = getFilter().split(";");
                if (result.length == 2) {
                    dataFunction = result[1];
                }
            }

        }
        return dataFunction;
    }

    public void setDataFunction(String dataFunction) {
        this.dataFunction = dataFunction;
    }

    public EvaluationInputObject getInputObject() {
        return inputObject;
    }

    public void setInputObject(EvaluationInputObject inputObject) {
        this.inputObject = inputObject;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getObjectName() {
        return ObjectName;
    }

    public void setObjectName(String ObjectName) {
        this.ObjectName = ObjectName;
    }

    public List<EvaluationInputObject> getLstEvaluationInputObject() {
        return lstEvaluationInputObject;
    }

    public void setLstEvaluationInputObject(List<EvaluationInputObject> lstEvaluationInputObject) {
        this.lstEvaluationInputObject = lstEvaluationInputObject;
    }

    public String getFilter() {
        return filter;
    }

    public void setFilter(String filter) {
        this.filter = filter;
    }
}

projectcamp/src/main/java/vn/viettel/campaign/entities/Rule.java
/*
 * Copyright 2009-2014 PrimeTek.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package vn.viettel.campaign.entities;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.io.Serializable;

/**
 * @author truongbx
 */
@Entity
@Table(name = "RULE")
@Getter
@Setter
public class Rule extends BaseCategory implements Serializable {

    @Id
    @Column(name = "RULE_ID")
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long ruleId;
    @Column(name = "DESCRIPTION")
    public String description;
    @Column(name = "RULE_NAME")
    public String ruleName;
    @Column(name = "CATEGORY_ID")
    private long categoryId;
    //HaBM2: Update change structure
    @Column(name = "CDR_SERVICE_IDS")
    private String cdrServiceId;
    
    @Transient
    public String segmentName;
    @Transient
    public long segmentId;
    @Transient
    public Integer priority;
    @Transient
    public Segment segment;
    @Transient
    private String name;
    
    public Rule() {
    }

    public Segment getSegment() {
        return segment;
    }

    public void setSegment(Segment segment) {
        if (segment!= null){
            this.segmentName = segment.getSegmentName();
            this.segmentId = segment.getSegmentId();
        }
        this.segment = segment;
    }


    public void setName(String name) {
        this.name = name;
    }
    @Override
    public long getParentId() {
        return getCategoryId();
    }

    @Override
    public String getTreeType() {
        return "rule_online";
    }

    @Override
    public void setParentId(Long id) {
        setCategoryId(id);
    }

    @Override
    public String getName() {
        return this.ruleName;
    }

    @Override
    public Class getParentType() {
        return Category.class;
    }
    public void asMap(Rule rule){
        this.ruleId = rule.getRuleId();
        this.ruleName = rule.getRuleName();
        this.description = rule.getDescription();
        this.categoryId = rule.getCategoryId();
        this.cdrServiceId = rule.getCdrServiceId();
    }
}

projectcamp/src/main/java/vn/viettel/campaign/controller/PreProcessDateController.java
package vn.viettel.campaign.controller;

import lombok.Getter;
import lombok.Setter;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;
import org.springframework.beans.factory.annotation.Autowired;
import vn.viettel.campaign.common.DataUtil;
import vn.viettel.campaign.common.DateUtils;
import vn.viettel.campaign.constants.Constants;
import vn.viettel.campaign.dto.FilterTable;
import vn.viettel.campaign.dto.PathTable;
import vn.viettel.campaign.dto.ProcessParamDTO;
import vn.viettel.campaign.entities.*;
import vn.viettel.campaign.service.PreprocessUnitInterface;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.*;

import static vn.viettel.campaign.common.DateUtils.DATETIME_PPU_SRING;
import static vn.viettel.campaign.common.DateUtils.DATETIME_PPU_ZONE;

import vn.viettel.campaign.validate.CheckOnEdit;

/**
 * @author truongbx
 * @date 9/15/2019
 */
@ManagedBean
@ViewScoped
@Getter
@Setter
public class PreProcessDateController extends BaseCategoryController<PreProcessUnit> implements Serializable {

    @Autowired
    PreprocessUnitInterface preprocessUnitServiceImpl;
    private TreeNode pathRootNode;
    private TreeNode selectedPathNode = new DefaultTreeNode();
    private List<InputObject> lstInputObject = new ArrayList<>();
    private Map<Long, InputObject> mapInputObject = new HashMap<>();
    private Map<String, InputObject> mapInputNameObject = new HashMap<>();
    private Map<Long, Function> mapFunction = new HashMap<>();
    private Map<Long, Function> mapFunctionTypeOne = new HashMap<>();
    private Map<Long, ProcessValue> mapProcessValue = new HashMap<>();
    private List<PathTable> lstPathTable = new ArrayList<>();
    private List<InputObject> lstConditionData = new ArrayList<>();
    private List<Function> lstFunctionData = new ArrayList<>();
    private List<Function> lstFunctionDataTypeOne = new ArrayList<>();
    private List<FilterTable> lstConditionTable = new ArrayList<>();
    private List<FilterTable> lstFunctionTable = new ArrayList<>();
    private List<FilterTable> lstFunctionPathTable = new ArrayList<>();
    private List<Zone> lstZone = new ArrayList<>();
    private List<ZoneMap> lstZoneMap = new ArrayList<>();
    private List<ProcessValue> lstProcessValue = new ArrayList<>();
    private List<ProcessValue> lstProcessValueTemp = new ArrayList<>();
    private List<ProcessParam> lstProcessParams = new ArrayList<>();
    private List<ProcessParamDTO> lstProcessParamDTO = new ArrayList<>();
    private boolean disableConditiontable = true;
    private PathTable currentPathTable = new PathTable();
    private PathTable realPathTable;
    private List<Long> hours;
    private List<Long> minAndSec;

    @Override
    public void init() {
        this.categoryType = Constants.CatagoryType.CATEORY_PRE_PROCESS_UNIT_DATE_TYPE;
        this.currentClass = PreProcessUnit.class;
        lstInputObject = preprocessUnitServiceImpl.getLstInputObject();
        for (InputObject inputObject : lstInputObject) {
            mapInputObject.put(inputObject.getObjectId(), inputObject);
            mapInputNameObject.put(inputObject.getObjectName() + "_" + inputObject.getObjectParentId(), inputObject);
        }
        initPathTree();
        lstFunctionData = preprocessUnitServiceImpl.getLstFunction();
        lstFunctionDataTypeOne = preprocessUnitServiceImpl.getLstFunctionTypeOne();
        lstFunctionData.forEach((e) -> mapFunction.put(e.getFunctionId(), e));
        lstFunctionDataTypeOne.forEach((e) -> mapFunction.put(e.getFunctionId(), e));
        lstZone = preprocessUnitServiceImpl.getLstZone();
        lstZoneMap = preprocessUnitServiceImpl.getLstZoneMap();
        hours = new ArrayList<>();
        minAndSec = new ArrayList<>();
        for (long i = 0; i <= 23; i++) {
            hours.add(i);
        }
        for (long i = 0; i <= 59; i++) {
            minAndSec.add(i);
        }
    }

    @Override
    public void initCurrentValue() {
        currentValue = preprocessUnitServiceImpl.getNextSequense();
//		TODO not sure
        currentValue.setPreProcessType(Constants.PRE_PROCESS_UNIT_DATE);
        onChangeCurrentTime();
    }

    @Override
    public boolean onValidateObject() {
        if (!validInputField(this.currentValue.getPreProcessName(), "PreProcess unit name", true, true, true)) {
            return false;
        }
        if (preprocessUnitServiceImpl.checkExistPreProcessName(this.currentValue.getPreProcessName(), this.currentValue.getPreProcessId())) {
            duplidateMessage("PreProcess unit name");
            return false;

        }
        if (!validInputField(this.currentValue.getDescription(), "Description", false, true, true)) {
            return false;
        }
        if (!validRequireField(this.currentValue.getDefaultValue(), "Default value")) {
            return false;
        }
        if (!validRequireField(this.currentValue.getInputMode(), "Input mode")) {
            return false;
        }

        if (this.currentValue.getInputMode() == 1) {
            if (!validRequireFieldList(lstPathTable, "Path table")) {
                return false;
            }
            for (PathTable pathTable : lstPathTable) {
                if (pathTable.getObjectId() == -1) {
                    notCompleteMessage("Path table");
                    return false;
                }
            }

        } else if (this.currentValue.getInputMode() == 2) {
            if (!validRequireFieldList(lstFunctionPathTable, "Path table")) {
                return false;
            }
            boolean validFunction = buildDataFunction(lstFunctionPathTable, 1);
            if (!validFunction) {
                notCompleteMessage("Path table");
                return false;
            }
        }
        if (!validRequireFieldList(lstProcessParams, "Normalizer table")) {
            return false;
        }
        //
        List<ProcessParam> lstData = new ArrayList<>();
        lstData.addAll(lstProcessParams);
        Collections.sort(lstData, new ProcessParamsComparator());
        Integer i = -1;
        Map<Long,String> map = new HashMap<>();
        for (ProcessParam processParam : lstData) {
            //

            map.put(processParam.getParamIndex(),"1");
            processParam.calculateConfigInput();
            if ((DataUtil.isStringNullOrEmpty(processParam.getStartVal()) && processParam.getStartType() == 3)
            || DataUtil.isNullObject(processParam.getStartValue()) && processParam.getStartType() == 1) {
                errorMsgParams(Constants.REMOTE_GROWL, utilsService.getTex("check.empty"), "Start value in normalizer table");
                return false;
            }
            if ((DataUtil.isStringNullOrEmpty(processParam.getEndVal()) && processParam.getEndType() == 3)
                    || DataUtil.isNullObject(processParam.getEndValue()) && processParam.getEndType() == 1) {
                errorMsgParams(Constants.REMOTE_GROWL, utilsService.getTex("check.empty"), "End value in normalizer table");
                return false;
            }
            if (!validRequireField(processParam.getPriority(), "Priority in normalizer table")) {
                return false;
            }

            if (i == processParam.getPriority()) {
                errorMsgParams(Constants.REMOTE_GROWL, utilsService.getTex("check.duplicate.table"), "priority", "normalizer");
                return false;
            }
            i = processParam.getPriority();
            //
            if (processParam.getStartType() == 1 && processParam.getEndType() == 1) {
                if (processParam.getStartValue().compareTo(processParam.getEndValue()) >= 0) {
                    errorMsgParams(Constants.REMOTE_GROWL, utilsService.getTex("check.start.end.val.1"));
                    return false;
                }
            }
            if ((processParam.getStartType() == 1 || processParam.getStartType() == 2)
                    && processParam.getEndType() == 3) {
                if (Integer.parseInt(processParam.getEndVal()) <= 0) {
                    errorMsgParams(Constants.REMOTE_GROWL, utilsService.getTex("check.start.end.val.2"));
                    return false;
                }
            }
            if (processParam.getStartType() == 2 && processParam.getEndType() == 2) {
                errorMsgParams(Constants.REMOTE_GROWL, utilsService.getTex("check.start.end.val.1"));
                return false;
            }

            if ((processParam.getEndType() == 1 || processParam.getEndType() == 2)
                    && processParam.getStartType() == 3) {
                if (Integer.parseInt(processParam.getStartVal()) <= 0) {
                    errorMsgParams(Constants.REMOTE_GROWL, utilsService.getTex("check.start.end.val.3"));
                    return false;
                }
            }

            if (processParam.getStartType() == 3 && processParam.getEndType() == 3) {
                if (!DataUtil.isNumber(processParam.getStartVal())) {
                    errorMsgParams(Constants.REMOTE_GROWL, utilsService.getTex("check.start.val.number"));
                    return false;
                }
                if (!DataUtil.isNumber(processParam.getEndVal())) {
                    errorMsgParams(Constants.REMOTE_GROWL, utilsService.getTex("check.end.val.number"));
                    return false;
                }
                if (Integer.parseInt(processParam.getStartVal()) >= Integer.parseInt(processParam.getEndVal())) {
                    errorMsgParams(Constants.REMOTE_GROWL, utilsService.getTex("check.start.end.val.1"));
                    return false;
                }
//                return false;
            }
        }
        lstProcessParams.forEach((e) -> {
            Long startType = e.getStartType();
            Long endType = e.getEndType();
            String startVal = "";

projectcamp/src/main/webapp/preProcessDate/ChoosePath.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<p:dialog header="Choose path" widgetVar="pathTreePopup" id="pathTreePopup" responsive="true" style="width: 500px"
          modal="true">
    <f:facet name="header">
        <i class="fa fa-list" style="font-size: 14px;"></i>
        <h:outputText value="Choose path" style="margin-left:10px;"/>
    </f:facet>
    <p:outputLabel value="Object path" style=" margin-left: 9px;"/>
    <div class="spacerHeight"/>
    <h:form id="pathTreeForm" style="width: 500px">
        <p:tree filterMatchMode="contains" id="pathTree" var="node"
                value="#{preProcessDateController.pathRootNode}"
                filterBy="#{node.objectName}"
                selectionMode="single"
                selection="#{preProcessDateController.selectedPathNode}"
                style=" border: 0px solid; padding: 0px;width: 500px;height:400px ;overflow-y: auto;">

            <p:treeNode type="root" expandedIcon="ui-icon-folder-open"
                        collapsedIcon="ui-icon-folder-collapsed">
                <h:outputText value="#{node.objectName}"/>
            </p:treeNode>

            <p:treeNode type="object" icon="ui-icon-document">
                <h:outputText value="#{node.objectName}"/>
            </p:treeNode>
        </p:tree>
        <div class="card card-w-title">
            <p:outputPanel class="ui-g-12 ui-lg-12">
                <p:commandButton action="#{preProcessDateController.validateChoosePath()}"
                                 style="width:auto;float: right;"
                                 icon="fa fa-chevron-down" value="Select"
                                 process="@([id$=pathTreeForm])"
                                 update="@([id$=tableForm]),@([id$=remoteGrowl]),@([id$=inputField])"
                                 oncomplete=" if (!args.validationFailed)   PF('pathTreePopup').hide();">
                </p:commandButton>
            </p:outputPanel>
        </div>
    </h:form>
</p:dialog>
</html>

projectcamp/src/main/webapp/preProcessDate/DefineValuePopup.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui" xmlns:ui="http://java.sun.com/jsf/facelets">

<p:dialog header="Define value" widgetVar="defineValueDialog" id="defineValueDialog" responsive="true" width="1000px"
          style=" overflow-y: hidden" dynamic="true" modal="true">
    <f:facet name="header">
        <i class="fa fa-list" style="font-size: 14px;"></i>
        <h:outputText value="Define value" style="margin-left:10px;"/>
    </f:facet>
    <!--<h:form id="createRuleForm">-->
    <h:form id="defineValueForm">

        <!--<h:form id="cdrForm">-->
        <p:outputPanel class="ui-g-12 ui-lg-12">
            <div class="spacerHeight"/>
            <p:dataTable id="defineValueTable" var="value" value="#{preProcessDateController.lstProcessValueTemp}"
                         selectionMode="single"
                         reflow="true" widgetVar="defineValueTable"
                         styleClass="table-campaign" style="margin-top: 10px;height: 450px ; overflow-y: auto"
                         paginator="true" rows="10"
                         rowKey="#{value.processValueId}"
                         editable="true"
                         rowsPerPageTemplate="5,10,15,20" lazy="false">
                <f:facet name="header">
                    <p:outputLabel value="Value table"
                                   style="float: left; font-weight: bold; font-size: 16px"/><span
                        style="color: red ;float: left">*</span>
                    <p:commandButton icon="fa fa-plus" value="Row" style="float: right; margin-left: 5px;width: 70px;"
                                     action="#{preProcessDateController.onAddDefineValue()}"
                                     update="@([id$=defineValueTable])"
                                     onstart="PF('defineValueTable').paginator.setPage(0);"/>
                </f:facet>
                <p:column headerText="Value Id" colspan="2">
                    <h:outputText value="#{value.valueId}" min="0"/>
                </p:column>
                <p:column headerText="Value Name" colspan="2">
                    <p:inputText onchange="this.value = this.value.trim()" placeholder="Value Name"
                                 value="#{value.valueName}">
                        <p:ajax  event="change" process="@([id$=defineValueForm])"  update="@([id$=defineValueForm])"></p:ajax>
                    </p:inputText>
                </p:column>
                <p:column headerText="Value Color" colspan="2">
                    <p:outputPanel class="ui-g-12 ui-lg-9">
                        <p:inputText onchange="this.value = this.value.trim()" placeholder="Value Color"
                                     value="#{value.valueColor}"
                                     id="valueColor">
                            <p:ajax  event="keyup"  update="@this,@([id$=colorPicker])" global="false"></p:ajax>
                        </p:inputText>
                    </p:outputPanel>
                    <p:outputPanel class="ui-g-12 ui-lg-3">
                        <p:colorPicker value="#{value.valueColor}" id="colorPicker">
                            <p:ajax  event="change"  update="@([id$=valueColor])" global="false"></p:ajax>
                        </p:colorPicker>
                    </p:outputPanel>
                </p:column>


                <p:column headerText="Description" colspan="2">
                    <p:inputText onchange="this.value = this.value.trim()" placeholder="Description"
                                 value="#{value.description}">
                        <p:ajax  event="change" process="@([id$=defineValueForm])"  update="@([id$=defineValueForm])"></p:ajax>
                    </p:inputText>
                </p:column>

                <p:column headerText="Action" colspan="1">
                    <p:commandLink action="#{preProcessDateController.onRemoveDefineValue(value)}"
                                   process=" @this "
                                   update="@([id$=defineValueTable]),@([id$=remoteGrowl])">
                        <h:outputText value="" class="ui-icon ui-icon-trash"  style=" width: 100%;"/>
                        <p:confirm header="Confirmation"
                                   message="Are you sure to delete this value?"
                                   icon="fa fa-warning"/>
                    </p:commandLink>
                </p:column>
            </p:dataTable>
        </p:outputPanel>

        <div class="card card-w-title">
            <p:outputPanel class="ui-g-12 ui-lg-12">
                <p:commandButton action="#{preProcessDateController.onSaveProcessValue()}"
                                 style="width:auto;float: right;"
                                 icon="fa fa-floppy-o" value="Apply"
                                 process=" @this ,@([id$=defineValueForm])"
                                 update="@([id$=tableForm]),@([id$=remoteGrowl])"
                                 oncomplete=" if (!args.validationFailed)   PF('defineValueDialog').hide();">
                    <p:ajax></p:ajax>
                </p:commandButton>
            </p:outputPanel>
        </div>
    </h:form>
</p:dialog>
</html>

projectcamp/src/main/webapp/preProcessDate/PreProcessDate.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                template="/WEB-INF/template_object.xhtml">

    <ui:define name="title">PreProcess unit - Date</ui:define>

    <ui:define name="viewname">PreProcess unit - Date</ui:define>
 
    <ui:define name="head">
        <style>
            body .ui-outputlabel {
                padding-bottom: 5px;
            }

            #basic1 .ui-panel-titlebar {
                padding: 0px;
                /*border-bottom: 0px solid;*/
            }

            body .ui-panel .ui-panel-content {
                padding: 0px;
            }
        </style>
        <script>
            // PF('segmentTable').addRow();
        </script>
    </ui:define>

    <ui:define name="content" >      
        <p:outputPanel class="ui-g ui-fluid" id="content">
            <p:outputPanel class="ui-g-12 ui-lg-3 panel_content" style="margin-top: -20px;">
                <ui:include src="preprocessAndCategoryTree.xhtml"/>
            </p:outputPanel>
            <p:outputPanel class="ui-g-12 ui-lg-9 panel_content" id="mainContent">
                <ui:include src="preprocessContent.xhtml"/>
            </p:outputPanel>
        </p:outputPanel> 
    </ui:define>
</ui:composition>

projectcamp/src/main/webapp/preProcessDate/categoryCreateOrEditPopup.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<p:dialog header="#{preProcessDateController.updateCategory eq false ? 'Create category' :'Update category'}"
          widgetVar="carDialog" id="carDialog" responsive="true" modal="true">
    <f:facet name="header">
        <i class="fa fa-list" style="font-size: 14px;"></i>
        <h:outputText value="#{preProcessDateController.updateCategory eq false ? 'Create category' :'Update category'}" style="margin-left:10px;"/>
    </f:facet>
    <h:form id="catagoryfrm" style="width: 635px !important">
        <p:outputPanel class="ui-g ui-fluid">
            <p:outputPanel class="ui-g-12 ui-lg-6">
                    <p:outputLabel value="Category id"/><span style="color: red">*</span>
                    <div class="spacerHeight"/>
                    <p:inputText onchange="this.value = this.value.trim()" placeholder="Category id"
                                 id="categoryId"
                                 readonly="true"
                                 value="#{preProcessDateController.category.categoryId}"
                                 requiredMessage="Category id is required"
                                 validatorMessage="Category id not contains '%' character">
                        <f:validateRegex pattern="^[^%]*$"/>
                    </p:inputText>
                </p:outputPanel>
            <p:outputPanel class="ui-g-12 ui-lg-6">
                <p:outputLabel value="Category name"/><span style="color: red">*</span>
                <div class="spacerHeight"/>
                <p:inputText onchange="this.value = this.value.trim()" placeholder="Category name"
                             id="categoryName"
                             value="#{preProcessDateController.category.name}"
                             title="#{preProcessDateController.category.name}"
                             requiredMessage="Category name is required"  autocomplete="off">

                    <p:ajax update="@this" process="@this" global="false"/>
                </p:inputText>
            </p:outputPanel>
            <p:outputPanel class="ui-g-12 ui-lg-6">
                <p:outputLabel value="Category type"/><span style="color: red">*</span>
                <div class="spacerHeight"/>
                <p:inputText onchange="this.value = this.value.trim()" placeholder="Category type"
                             readonly="true"
                             id="categoryType"
                             required="true"
                             value="PPU Date"
                             requiredMessage="Category type is require"/>
            </p:outputPanel>

            <p:outputPanel class="ui-g-12 ui-lg-6" rendered="#{preProcessDateController.category.parentId != null}">
                <p:outputLabel value="Parent category"/>
                <div class="spacerHeight"/>
                <p:selectOneMenu  syncTooltip="true"  filterMatchMode="contains"  filter="true" style="margin-bottom:10px;"
                                 value="#{preProcessDateController.category.parentId}"
                                 id="parentCategory"
                                 rendered="#{preProcessDateController.updateCategory eq false}">
                    <f:selectItems value="#{preProcessDateController.categories}"
                                   var="item"
                                   itemLabel="#{item.name}" itemDescription="#{item.name}" 
                                   itemValue="#{item.categoryId}"/>
                </p:selectOneMenu>
                <p:selectOneMenu  syncTooltip="true"  filterMatchMode="contains"  filter="true" style="margin-bottom:10px;"
                                 value="#{preProcessDateController.category.parentId}"
                                 id="parentCategoryEdit"
                                 rendered="#{preProcessDateController.updateCategory eq true}">
    
                    <f:selectItems value="#{preProcessDateController.categories}"
                                   var="item"
                                   itemLabel="#{item.name}" itemDescription="#{item.name}" 
                                   itemValue="#{item.categoryId}"/>
                </p:selectOneMenu>
            </p:outputPanel>
            <p:outputPanel class="ui-g-12 ui-lg-6"></p:outputPanel>
        </p:outputPanel>

        <div class="card card-w-title">
            <p:outputPanel class="ui-g-12 ui-lg-12">
                <p:commandButton icon="fa fa-remove" value="Cancel"
                                 style="width:auto;float: right;"
                                 process="@this"
                                 oncomplete="PF('carDialog').hide();"/>
                    <p:commandButton action="#{preProcessDateController.validateCategory()}"
                                     style="width:auto;float: right;" 
                                      icon="fa fa-floppy-o" value="Save"
                                     process="@([id$=catagoryfrm])"
                                     update="@([id$=remoteGrowl])"
                                     oncomplete="if (!args.validationFailed) PF('dlgConfirm').show();">
                    </p:commandButton>
                </p:outputPanel>
            </div>
        </h:form>
    </p:dialog>

<p:dialog header="Confirmation" widgetVar="dlgConfirm" modal="true" height="100" id="categoryConfirm">
    <h:outputText value="#{preProcessDateController.updateCategory eq false ? 'Are you sure to create this Category?' : 'Are you sure to edit this Category?'}" />

    <div class="card card-w-title">
        <p:outputPanel class="ui-g-12 ui-lg-12">
            <p:commandButton value="No"
                             style="width:auto;float: right;"
                             process="@this"
                             oncomplete="PF('dlgConfirm').hide();"/>

            <p:commandButton action="#{preProcessDateController.doSaveOrUpdateCategory()}"
                             style="width:auto;float: right;"
                             value="Yes"
                             process="@([id$=catagoryfrm]),@this"
                             update="@([id$=fromTree]),@([id$=remoteGrowl])"
                             oncomplete="PF('dlgConfirm').hide();PF('carDialog').hide();">
            </p:commandButton>
        </p:outputPanel>
    </div>
</p:dialog>
</html>